server: 
  port: 8888

spring: 
#  main: 
#      allow-bean-definition-overriding: true
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haowangjiadb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    druid: 
      
    #初始化连接池大小
      initialSize: 50
    #最大连接数
      maxActive: 300
    #最小连接数
      minIdle: 5
    #获取连接的最大等待时间
      maxWait: 10000
    #解决mysql8小时的问题
      validationgQuery: SELECT 'X'
    #空闲连接的检查时间间隔
      timeBetweenEvictionRunsMillis: 60000
    #空闲连接最小空闲时间
      minEvictableIdleTimeMillis: 300000
    #不影响性能，并且保证安全性
      testWhileIdle: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
    
mybatis: 
    type-aliases-package: com.test.sibo.mapper
    mapper-locations: classpath:mybatis/*.xml      

jwt:
  # 存放Token的Header Key
  header: Authorization
  # 密匙key
  secret: mySecret
  # 过期时间   单位秒 7天后过期  604800
  expiration: 3600
  # 自定义token 前缀字符
  tokenHead: Bearer-
  # 超时时间   单位秒
  access_token: 3600
  # 刷新token时间   单位秒
  refresh_token: 3600
 
    

